// @ts-check

// This runs in Node.js — don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar is autogenerated from the filesystem under `../docs`.
 * Order is controlled per-file via `sidebar_position` frontmatter and per-folder
 * via `_category_.json`.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
